#!/bin/bash
set -e
cd /Users/tea/Documents/GPUDBMetalBenchmarkLC
f1="codegen/metal_codegen.cpp"
f2="codegen/query_executor.cpp"

# === KERNEL NAME RENAMES (Metal function names + findPSO refs) ===
for f in "$f1" "$f2"; do
  sed -i '' 's/gen_q1_fused/Q1_reduce/g' "$f"
  sed -i '' 's/q1_rf_index/Q1_rf_index/g' "$f"
  sed -i '' 's/q1_ls_index/Q1_ls_index/g' "$f"
  sed -i '' 's/gen_q2_filter_part/Q2_bitmap_build/g' "$f"
  sed -i '' 's/gen_q2_find_min_cost/Q2_atomic_min/g' "$f"
  sed -i '' 's/gen_q2_match_suppliers/Q2_compact/g' "$f"
  sed -i '' 's/gen_q3_build_customer_bitmap/Q3_bitmap_build/g' "$f"
  sed -i '' 's/gen_q3_build_orders_map/Q3_map_build/g' "$f"
  sed -i '' 's/gen_q3_probe_agg/Q3_probe_agg/g' "$f"
  sed -i '' 's/gen_q3_compact/Q3_compact/g' "$f"
  sed -i '' 's/gen_q4_build_late_bitmap/Q4_bitmap_build/g' "$f"
  sed -i '' 's/gen_q4_count_stage1/Q4_reduce/g' "$f"
  sed -i '' 's/gen_q4_count_stage2/Q4_reduce_final/g' "$f"
  sed -i '' 's/gen_q5_build_customer_nation_map/Q5_map_build_cust/g' "$f"
  sed -i '' 's/gen_q5_build_supplier_nation_map/Q5_map_build_supp/g' "$f"
  sed -i '' 's/gen_q5_build_orders_map/Q5_map_build_orders/g' "$f"
  sed -i '' 's/gen_q5_probe_and_aggregate/Q5_probe_agg/g' "$f"
  sed -i '' 's/gen_q6_stage1/Q6_reduce/g' "$f"
  sed -i '' 's/gen_q6_stage2/Q6_reduce_final/g' "$f"
  sed -i '' 's/gen_q7_build_supplier_map/Q7_map_build_supp/g' "$f"
  sed -i '' 's/gen_q7_build_customer_map/Q7_map_build_cust/g' "$f"
  sed -i '' 's/gen_q7_build_orders_map/Q7_map_build_orders/g' "$f"
  sed -i '' 's/gen_q7_probe_and_aggregate/Q7_probe_agg/g' "$f"
  sed -i '' 's/gen_q8_build_orders_map/Q8_map_build/g' "$f"
  sed -i '' 's/gen_q8_probe_and_aggregate/Q8_probe_agg/g' "$f"
  sed -i '' 's/gen_q9_build_part_bitmap/Q9_bitmap_build/g' "$f"
  sed -i '' 's/gen_q9_build_supplier_map/Q9_map_build/g' "$f"
  sed -i '' 's/gen_q9_build_partsupp_ht/Q9_ht_build_partsupp/g' "$f"
  sed -i '' 's/gen_q9_build_orders_ht/Q9_ht_build_orders/g' "$f"
  sed -i '' 's/gen_q9_probe_and_aggregate/Q9_probe_agg/g' "$f"
  sed -i '' 's/gen_q10_build_orders_map/Q10_map_build/g' "$f"
  sed -i '' 's/gen_q10_probe_and_aggregate/Q10_probe_agg/g' "$f"
  sed -i '' 's/gen_q11_aggregate_value/Q11_atomic_agg/g' "$f"
  sed -i '' 's/gen_q11_aggregate/Q11_atomic_agg/g' "$f"
  sed -i '' 's/gen_q12_build_priority_bitmap/Q12_bitmap_build/g' "$f"
  sed -i '' 's/gen_q12_filter_stage1/Q12_reduce/g' "$f"
  sed -i '' 's/gen_q12_filter_stage2/Q12_reduce_final/g' "$f"
  sed -i '' 's/gen_q13_count_orders/Q13_str_match_count/g' "$f"
  sed -i '' 's/gen_q13_histogram/Q13_histogram/g' "$f"
  sed -i '' 's/gen_q14_stage1/Q14_reduce/g' "$f"
  sed -i '' 's/gen_q14_stage2/Q14_reduce_final/g' "$f"
  sed -i '' 's/gen_q15_aggregate_revenue/Q15_atomic_agg/g' "$f"
  sed -i '' 's/gen_q16_scan_and_bitmap/Q16_group_bitmap/g' "$f"
  sed -i '' 's/gen_q16_popcount/Q16_popcount/g' "$f"
  sed -i '' 's/gen_q17_aggregate_qty_stats/Q17_atomic_agg/g' "$f"
  sed -i '' 's/gen_q17_sum_revenue/Q17_probe_reduce/g' "$f"
  sed -i '' 's/gen_q18_aggregate_quantity/Q18_atomic_agg/g' "$f"
  sed -i '' 's/gen_q18_filter_orders/Q18_compact/g' "$f"
  sed -i '' 's/gen_q19_build_part_group_map/Q19_map_classify/g' "$f"
  sed -i '' 's/gen_q19_shipmode_filter/Q19_str_filter/g' "$f"
  sed -i '' 's/gen_q19_sum_stage1/Q19_reduce/g' "$f"
  sed -i '' 's/gen_q19_sum_stage2/Q19_reduce_final/g' "$f"
  sed -i '' 's/gen_q20_aggregate_lineitem/Q20_ht_agg/g' "$f"
  sed -i '' 's/gen_q20_probe_partsupp/Q20_probe_check/g' "$f"
  sed -i '' 's/gen_q21_build_order_tracking/Q21_track_build/g' "$f"
  sed -i '' 's/gen_q21_count_qualifying/Q21_count_qualify/g' "$f"
  sed -i '' 's/gen_q22_avg_balance/Q22_scalar_agg/g' "$f"
  sed -i '' 's/gen_q22_build_orders_bitmap/Q22_bitmap_build/g' "$f"
  sed -i '' 's/gen_q22_final_aggregate/Q22_bin_agg/g' "$f"
done

# === C++ FUNCTION NAME RENAMES (in metal_codegen.cpp only) ===
sed -i '' 's/void generateQ1Kernels/void emitQ1_TwoStageReduce/g' "$f1"
sed -i '' 's/void generateQ2Kernels/void emitQ2_BitmapMinCompact/g' "$f1"
sed -i '' 's/void generateQ3Kernels/void emitQ3_BitmapMapProbeCompact/g' "$f1"
sed -i '' 's/void generateQ4Kernels/void emitQ4_BitmapReduce/g' "$f1"
sed -i '' 's/void generateQ5Kernels/void emitQ5_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/void generateQ6Kernels/void emitQ6_TwoStageReduce/g' "$f1"
sed -i '' 's/void generateQ7Kernels/void emitQ7_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/void generateQ8Kernels/void emitQ8_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/void generateQ9Kernels/void emitQ9_BitmapMapHTProbeAgg/g' "$f1"
sed -i '' 's/void generateQ10Kernels/void emitQ10_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/void generateQ11Kernels/void emitQ11_AtomicAgg/g' "$f1"
sed -i '' 's/void generateQ12Kernels/void emitQ12_BitmapReduce/g' "$f1"
sed -i '' 's/void generateQ13Kernels/void emitQ13_StrMatchHistogram/g' "$f1"
sed -i '' 's/void generateQ14Kernels/void emitQ14_TwoStageReduce/g' "$f1"
sed -i '' 's/void generateQ15Kernels/void emitQ15_AtomicAgg/g' "$f1"
sed -i '' 's/void generateQ16Kernels/void emitQ16_GroupBitmapPopcount/g' "$f1"
sed -i '' 's/void generateQ17Kernels/void emitQ17_AtomicAggProbeReduce/g' "$f1"
sed -i '' 's/void generateQ18Kernels/void emitQ18_AtomicAggCompact/g' "$f1"
sed -i '' 's/void generateQ19Kernels/void emitQ19_MapClassifyStrFilterReduce/g' "$f1"
sed -i '' 's/void generateQ20Kernels/void emitQ20_HTAggProbeCheck/g' "$f1"
sed -i '' 's/void generateQ21Kernels/void emitQ21_TrackBuildCountQualify/g' "$f1"
sed -i '' 's/void generateQ22Kernels/void emitQ22_ScalarAggBitmapBinAgg/g' "$f1"

# === UPDATE generateMetal() dispatcher to use new function names ===
sed -i '' 's/generateQ1Kernels/emitQ1_TwoStageReduce/g' "$f1"
sed -i '' 's/generateQ2Kernels/emitQ2_BitmapMinCompact/g' "$f1"
sed -i '' 's/generateQ3Kernels/emitQ3_BitmapMapProbeCompact/g' "$f1"
sed -i '' 's/generateQ4Kernels/emitQ4_BitmapReduce/g' "$f1"
sed -i '' 's/generateQ5Kernels/emitQ5_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/generateQ6Kernels/emitQ6_TwoStageReduce/g' "$f1"
sed -i '' 's/generateQ7Kernels/emitQ7_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/generateQ8Kernels/emitQ8_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/generateQ9Kernels/emitQ9_BitmapMapHTProbeAgg/g' "$f1"
sed -i '' 's/generateQ10Kernels/emitQ10_MapBuildProbeAgg/g' "$f1"
sed -i '' 's/generateQ11Kernels/emitQ11_AtomicAgg/g' "$f1"
sed -i '' 's/generateQ12Kernels/emitQ12_BitmapReduce/g' "$f1"
sed -i '' 's/generateQ13Kernels/emitQ13_StrMatchHistogram/g' "$f1"
sed -i '' 's/generateQ14Kernels/emitQ14_TwoStageReduce/g' "$f1"
sed -i '' 's/generateQ15Kernels/emitQ15_AtomicAgg/g' "$f1"
sed -i '' 's/generateQ16Kernels/emitQ16_GroupBitmapPopcount/g' "$f1"
sed -i '' 's/generateQ17Kernels/emitQ17_AtomicAggProbeReduce/g' "$f1"
sed -i '' 's/generateQ18Kernels/emitQ18_AtomicAggCompact/g' "$f1"
sed -i '' 's/generateQ19Kernels/emitQ19_MapClassifyStrFilterReduce/g' "$f1"
sed -i '' 's/generateQ20Kernels/emitQ20_HTAggProbeCheck/g' "$f1"
sed -i '' 's/generateQ21Kernels/emitQ21_TrackBuildCountQualify/g' "$f1"
sed -i '' 's/generateQ22Kernels/emitQ22_ScalarAggBitmapBinAgg/g' "$f1"

# === UPDATE SECTION HEADERS ===
sed -i '' 's|// === Q1 KERNEL GENERATOR ===|// === PATTERN: Two-Stage Reduce (Q1 — 6-bin fused reduce) ===|g' "$f1"
sed -i '' 's|// === Q6 KERNEL GENERATOR ===|// === PATTERN: Two-Stage Reduce (Q6 — single-sum filter+reduce) ===|g' "$f1"
sed -i '' 's|// === Q3 KERNEL GENERATOR ===|// === PATTERN: Bitmap Build + Map Build + Probe-Agg + Compact (Q3) ===|g' "$f1"
sed -i '' 's|// === Q14 KERNEL GENERATOR ===|// === PATTERN: Two-Stage Reduce with Bitmap Probe (Q14) ===|g' "$f1"
sed -i '' 's|// === Q4 KERNEL GENERATOR ===|// === PATTERN: Bitmap Build + N-bin Reduce (Q4) ===|g' "$f1"
sed -i '' 's|// === Q12 KERNEL GENERATOR ===|// === PATTERN: Bitmap Build + N-bin Reduce (Q12) ===|g' "$f1"
sed -i '' 's|// === Q19 KERNEL GENERATOR ===|// === PATTERN: Map Classify + String Filter + Reduce (Q19) ===|g' "$f1"
sed -i '' 's|// === Q15 KERNEL GENERATOR ===|// === PATTERN: Atomic Map Aggregate (Q15) ===|g' "$f1"

echo "All renames complete."
